#include "PORT_cfg.h"
#include "PORT.h"

#if (CONFIG_TYPE == POST_COMPILE)
PORT_StrPinCfg_t PORT_StrPinsConfig={{
		PORT_enuInput_PU,
		PORT_enuInput_HI,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_LOW,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH,
		PORT_enuOUTPUT_HIGH
}};

#endif 