#include "PORT_cfg.h"
#include "PORT.h"
#include "stdRegs.h"
#include "Typedefs.h"
#include "Bit_Math.h"

#if (CONFIG_TYPE == PRE_COMPILE)
void PORT_vInit()
{
#if (PORT_PIN0 == PORT_INPUT_PU)
	#define PORT_PIN0_DIR PORT_LOW
	#define PORT_PIN0_PORT PORT_HIGH
#elif (PORT_PIN0 == PORT_INPUT_HI)
	#define PORT_PIN0_DIR PORT_LOW
	#define PORT_PIN0_PORT PORT_LOW
#elif (PORT_PIN0 == PORT_OUTPUT_HIGH)
	#define PORT_PIN0_DIR PORT_HIGH
	#define PORT_PIN0_PORT PORT_HIGH
#elif (PORT_PIN0 == PORT_OUTPUT_LOW)
	#define PORT_PIN0_DIR PORT_HIGH
	#define PORT_PIN0_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN1 == PORT_INPUT_PU)
	#define PORT_PIN1_DIR PORT_LOW
	#define PORT_PIN1_PORT PORT_HIGH
#elif (PORT_PIN1 == PORT_INPUT_HI)
	#define PORT_PIN1_DIR PORT_LOW
	#define PORT_PIN1_PORT PORT_LOW
#elif (PORT_PIN1 == PORT_OUTPUT_HIGH)
	#define PORT_PIN1_DIR PORT_HIGH
	#define PORT_PIN1_PORT PORT_HIGH
#elif (PORT_PIN1 == PORT_OUTPUT_LOW)
	#define PORT_PIN1_DIR PORT_HIGH
	#define PORT_PIN1_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif

	
#if (PORT_PIN2 == PORT_INPUT_PU)
	#define PORT_PIN2_DIR PORT_LOW
	#define PORT_PIN2_PORT PORT_HIGH
#elif (PORT_PIN2 == PORT_INPUT_HI)
	#define PORT_PIN2_DIR PORT_LOW
	#define PORT_PIN2_PORT PORT_LOW
#elif (PORT_PIN2 == PORT_OUTPUT_HIGH)
	#define PORT_PIN2_DIR PORT_HIGH
	#define PORT_PIN2_PORT PORT_HIGH
#elif (PORT_PIN2 == PORT_OUTPUT_LOW)
	#define PORT_PIN2_DIR PORT_HIGH
	#define PORT_PIN2_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN3 == PORT_INPUT_PU)
	#define PORT_PIN3_DIR PORT_LOW
	#define PORT_PIN3_PORT PORT_HIGH
#elif (PORT_PIN3 == PORT_INPUT_HI)
	#define PORT_PIN3_DIR PORT_LOW
	#define PORT_PIN3_PORT PORT_LOW
#elif (PORT_PIN3 == PORT_OUTPUT_HIGH)
	#define PORT_PIN3_DIR PORT_HIGH
	#define PORT_PIN3_PORT PORT_HIGH
#elif (PORT_PIN3 == PORT_OUTPUT_LOW)
	#define PORT_PIN3_DIR PORT_HIGH
	#define PORT_PIN3_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN4 == PORT_INPUT_PU)
	#define PORT_PIN4_DIR PORT_LOW
	#define PORT_PIN4_PORT PORT_HIGH
#elif (PORT_PIN4 == PORT_INPUT_HI)
	#define PORT_PIN4_DIR PORT_LOW
	#define PORT_PIN4_PORT PORT_LOW
#elif (PORT_PIN4 == PORT_OUTPUT_HIGH)
	#define PORT_PIN4_DIR PORT_HIGH
	#define PORT_PIN4_PORT PORT_HIGH
#elif (PORT_PIN4 == PORT_OUTPUT_LOW)
	#define PORT_PIN4_DIR PORT_HIGH
	#define PORT_PIN4_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN5 == PORT_INPUT_PU)
	#define PORT_PIN5_DIR PORT_LOW
	#define PORT_PIN5_PORT PORT_HIGH
#elif (PORT_PIN5 == PORT_INPUT_HI)
	#define PORT_PIN5_DIR PORT_LOW
	#define PORT_PIN5_PORT PORT_LOW
#elif (PORT_PIN5 == PORT_OUTPUT_HIGH)
	#define PORT_PIN5_DIR PORT_HIGH
	#define PORT_PIN5_PORT PORT_HIGH
#elif (PORT_PIN5 == PORT_OUTPUT_LOW)
	#define PORT_PIN5_DIR PORT_HIGH
	#define PORT_PIN5_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN6 == PORT_INPUT_PU)
	#define PORT_PIN6_DIR PORT_LOW
	#define PORT_PIN6_PORT PORT_HIGH
#elif (PORT_PIN6 == PORT_INPUT_HI)
	#define PORT_PIN6_DIR PORT_LOW
	#define PORT_PIN6_PORT PORT_LOW
#elif (PORT_PIN6 == PORT_OUTPUT_HIGH)
	#define PORT_PIN6_DIR PORT_HIGH
	#define PORT_PIN6_PORT PORT_HIGH
#elif (PORT_PIN6 == PORT_OUTPUT_LOW)
	#define PORT_PIN6_DIR PORT_HIGH
	#define PORT_PIN6_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN7 == PORT_INPUT_PU)
	#define PORT_PIN7_DIR PORT_LOW
	#define PORT_PIN7_PORT PORT_HIGH
#elif (PORT_PIN7 == PORT_INPUT_HI)
	#define PORT_PIN7_DIR PORT_LOW
	#define PORT_PIN7_PORT PORT_LOW
#elif (PORT_PIN7 == PORT_OUTPUT_HIGH)
	#define PORT_PIN7_DIR PORT_HIGH
	#define PORT_PIN7_PORT PORT_HIGH
#elif (PORT_PIN7 == PORT_OUTPUT_LOW)
	#define PORT_PIN7_DIR PORT_HIGH
	#define PORT_PIN7_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN8 == PORT_INPUT_PU)
	#define PORT_PIN8_DIR PORT_LOW
	#define PORT_PIN8_PORT PORT_HIGH
#elif (PORT_PIN8 == PORT_INPUT_HI)
	#define PORT_PIN8_DIR PORT_LOW
	#define PORT_PIN8_PORT PORT_LOW
#elif (PORT_PIN8 == PORT_OUTPUT_HIGH)
	#define PORT_PIN8_DIR PORT_HIGH
	#define PORT_PIN8_PORT PORT_HIGH
#elif (PORT_PIN8 == PORT_OUTPUT_LOW)
	#define PORT_PIN8_DIR PORT_HIGH
	#define PORT_PIN8_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN9 == PORT_INPUT_PU)
	#define PORT_PIN9_DIR PORT_LOW
	#define PORT_PIN9_PORT PORT_HIGH
#elif (PORT_PIN9 == PORT_INPUT_HI)
	#define PORT_PIN9_DIR PORT_LOW
	#define PORT_PIN9_PORT PORT_LOW
#elif (PORT_PIN9 == PORT_OUTPUT_HIGH)
	#define PORT_PIN9_DIR PORT_HIGH
	#define PORT_PIN9_PORT PORT_HIGH
#elif (PORT_PIN9 == PORT_OUTPUT_LOW)
	#define PORT_PIN9_DIR PORT_HIGH
	#define PORT_PIN9_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN10 == PORT_INPUT_PU)
	#define PORT_PIN10_DIR PORT_LOW
	#define PORT_PIN10_PORT PORT_HIGH
#elif (PORT_PIN10 == PORT_INPUT_HI)
	#define PORT_PIN10_DIR PORT_LOW
	#define PORT_PIN10_PORT PORT_LOW
#elif (PORT_PIN10 == PORT_OUTPUT_HIGH)
	#define PORT_PIN10_DIR PORT_HIGH
	#define PORT_PIN10_PORT PORT_HIGH
#elif (PORT_PIN10 == PORT_OUTPUT_LOW)
	#define PORT_PIN10_DIR PORT_HIGH
	#define PORT_PIN10_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN11 == PORT_INPUT_PU)
	#define PORT_PIN11_DIR PORT_LOW
	#define PORT_PIN11_PORT PORT_HIGH
#elif (PORT_PIN11 == PORT_INPUT_HI)
	#define PORT_PIN11_DIR PORT_LOW
	#define PORT_PIN11_PORT PORT_LOW
#elif (PORT_PIN11 == PORT_OUTPUT_HIGH)
	#define PORT_PIN11_DIR PORT_HIGH
	#define PORT_PIN11_PORT PORT_HIGH
#elif (PORT_PIN11 == PORT_OUTPUT_LOW)
	#define PORT_PIN11_DIR PORT_HIGH
	#define PORT_PIN11_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN12 == PORT_INPUT_PU)
	#define PORT_PIN12_DIR PORT_LOW
	#define PORT_PIN12_PORT PORT_HIGH
#elif (PORT_PIN12 == PORT_INPUT_HI)
	#define PORT_PIN12_DIR PORT_LOW
	#define PORT_PIN12_PORT PORT_LOW
#elif (PORT_PIN12 == PORT_OUTPUT_HIGH)
	#define PORT_PIN12_DIR PORT_HIGH
	#define PORT_PIN12_PORT PORT_HIGH
#elif (PORT_PIN12 == PORT_OUTPUT_LOW)
	#define PORT_PIN12_DIR PORT_HIGH
	#define PORT_PIN12_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN13 == PORT_INPUT_PU)
	#define PORT_PIN13_DIR PORT_LOW
	#define PORT_PIN13_PORT PORT_HIGH
#elif (PORT_PIN13 == PORT_INPUT_HI)
	#define PORT_PIN13_DIR PORT_LOW
	#define PORT_PIN13_PORT PORT_LOW
#elif (PORT_PIN13 == PORT_OUTPUT_HIGH)
	#define PORT_PIN13_DIR PORT_HIGH
	#define PORT_PIN13_PORT PORT_HIGH
#elif (PORT_PIN13 == PORT_OUTPUT_LOW)
	#define PORT_PIN13_DIR PORT_HIGH
	#define PORT_PIN13_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN14 == PORT_INPUT_PU)
	#define PORT_PIN14_DIR PORT_LOW
	#define PORT_PIN14_PORT PORT_HIGH
#elif (PORT_PIN14 == PORT_INPUT_HI)
	#define PORT_PIN14_DIR PORT_LOW
	#define PORT_PIN14_PORT PORT_LOW
#elif (PORT_PIN14 == PORT_OUTPUT_HIGH)
	#define PORT_PIN14_DIR PORT_HIGH
	#define PORT_PIN14_PORT PORT_HIGH
#elif (PORT_PIN14 == PORT_OUTPUT_LOW)
	#define PORT_PIN14_DIR PORT_HIGH
	#define PORT_PIN14_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN15 == PORT_INPUT_PU)
	#define PORT_PIN15_DIR PORT_LOW
	#define PORT_PIN15_PORT PORT_HIGH
#elif (PORT_PIN15 == PORT_INPUT_HI)
	#define PORT_PIN15_DIR PORT_LOW
	#define PORT_PIN15_PORT PORT_LOW
#elif (PORT_PIN15 == PORT_OUTPUT_HIGH)
	#define PORT_PIN15_DIR PORT_HIGH
	#define PORT_PIN15_PORT PORT_HIGH
#elif (PORT_PIN15 == PORT_OUTPUT_LOW)
	#define PORT_PIN15_DIR PORT_HIGH
	#define PORT_PIN15_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN16 == PORT_INPUT_PU)
	#define PORT_PIN16_DIR PORT_LOW
	#define PORT_PIN16_PORT PORT_HIGH
#elif (PORT_PIN16 == PORT_INPUT_HI)
	#define PORT_PIN16_DIR PORT_LOW
	#define PORT_PIN16_PORT PORT_LOW
#elif (PORT_PIN16 == PORT_OUTPUT_HIGH)
	#define PORT_PIN16_DIR PORT_HIGH
	#define PORT_PIN16_PORT PORT_HIGH
#elif (PORT_PIN16 == PORT_OUTPUT_LOW)
	#define PORT_PIN16_DIR PORT_HIGH
	#define PORT_PIN16_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN17 == PORT_INPUT_PU)
	#define PORT_PIN17_DIR PORT_LOW
	#define PORT_PIN17_PORT PORT_HIGH
#elif (PORT_PIN17 == PORT_INPUT_HI)
	#define PORT_PIN17_DIR PORT_LOW
	#define PORT_PIN17_PORT PORT_LOW
#elif (PORT_PIN17 == PORT_OUTPUT_HIGH)
	#define PORT_PIN17_DIR PORT_HIGH
	#define PORT_PIN17_PORT PORT_HIGH
#elif (PORT_PIN17 == PORT_OUTPUT_LOW)
	#define PORT_PIN17_DIR PORT_HIGH
	#define PORT_PIN17_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN18 == PORT_INPUT_PU)
	#define PORT_PIN18_DIR PORT_LOW
	#define PORT_PIN18_PORT PORT_HIGH
#elif (PORT_PIN18 == PORT_INPUT_HI)
	#define PORT_PIN18_DIR PORT_LOW
	#define PORT_PIN18_PORT PORT_LOW
#elif (PORT_PIN18 == PORT_OUTPUT_HIGH)
	#define PORT_PIN18_DIR PORT_HIGH
	#define PORT_PIN18_PORT PORT_HIGH
#elif (PORT_PIN18 == PORT_OUTPUT_LOW)
	#define PORT_PIN18_DIR PORT_HIGH
	#define PORT_PIN18_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN19 == PORT_INPUT_PU)
	#define PORT_PIN19_DIR PORT_LOW
	#define PORT_PIN19_PORT PORT_HIGH
#elif (PORT_PIN19 == PORT_INPUT_HI)
	#define PORT_PIN19_DIR PORT_LOW
	#define PORT_PIN19_PORT PORT_LOW
#elif (PORT_PIN19 == PORT_OUTPUT_HIGH)
	#define PORT_PIN19_DIR PORT_HIGH
	#define PORT_PIN19_PORT PORT_HIGH
#elif (PORT_PIN19 == PORT_OUTPUT_LOW)
	#define PORT_PIN19_DIR PORT_HIGH
	#define PORT_PIN19_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN20 == PORT_INPUT_PU)
	#define PORT_PIN20_DIR PORT_LOW
	#define PORT_PIN20_PORT PORT_HIGH
#elif (PORT_PIN20 == PORT_INPUT_HI)
	#define PORT_PIN20_DIR PORT_LOW
	#define PORT_PIN20_PORT PORT_LOW
#elif (PORT_PIN20 == PORT_OUTPUT_HIGH)
	#define PORT_PIN20_DIR PORT_HIGH
	#define PORT_PIN20_PORT PORT_HIGH
#elif (PORT_PIN20 == PORT_OUTPUT_LOW)
	#define PORT_PIN20_DIR PORT_HIGH
	#define PORT_PIN20_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN21 == PORT_INPUT_PU)
	#define PORT_PIN21_DIR PORT_LOW
	#define PORT_PIN21_PORT PORT_HIGH
#elif (PORT_PIN21 == PORT_INPUT_HI)
	#define PORT_PIN21_DIR PORT_LOW
	#define PORT_PIN21_PORT PORT_LOW
#elif (PORT_PIN21 == PORT_OUTPUT_HIGH)
	#define PORT_PIN21_DIR PORT_HIGH
	#define PORT_PIN21_PORT PORT_HIGH
#elif (PORT_PIN21 == PORT_OUTPUT_LOW)
	#define PORT_PIN21_DIR PORT_HIGH
	#define PORT_PIN21_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN22 == PORT_INPUT_PU)
	#define PORT_PIN22_DIR PORT_LOW
	#define PORT_PIN22_PORT PORT_HIGH
#elif (PORT_PIN22 == PORT_INPUT_HI)
	#define PORT_PIN22_DIR PORT_LOW
	#define PORT_PIN22_PORT PORT_LOW
#elif (PORT_PIN22 == PORT_OUTPUT_HIGH)
	#define PORT_PIN22_DIR PORT_HIGH
	#define PORT_PIN22_PORT PORT_HIGH
#elif (PORT_PIN22 == PORT_OUTPUT_LOW)
	#define PORT_PIN22_DIR PORT_HIGH
	#define PORT_PIN22_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN23 == PORT_INPUT_PU)
	#define PORT_PIN23_DIR PORT_LOW
	#define PORT_PIN23_PORT PORT_HIGH
#elif (PORT_PIN23 == PORT_INPUT_HI)
	#define PORT_PIN23_DIR PORT_LOW
	#define PORT_PIN23_PORT PORT_LOW
#elif (PORT_PIN23 == PORT_OUTPUT_HIGH)
	#define PORT_PIN23_DIR PORT_HIGH
	#define PORT_PIN23_PORT PORT_HIGH
#elif (PORT_PIN23 == PORT_OUTPUT_LOW)
	#define PORT_PIN23_DIR PORT_HIGH
	#define PORT_PIN23_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN24 == PORT_INPUT_PU)
	#define PORT_PIN24_DIR PORT_LOW
	#define PORT_PIN24_PORT PORT_HIGH
#elif (PORT_PIN24 == PORT_INPUT_HI)
	#define PORT_PIN24_DIR PORT_LOW
	#define PORT_PIN24_PORT PORT_LOW
#elif (PORT_PIN24 == PORT_OUTPUT_HIGH)
	#define PORT_PIN24_DIR PORT_HIGH
	#define PORT_PIN24_PORT PORT_HIGH
#elif (PORT_PIN24 == PORT_OUTPUT_LOW)
	#define PORT_PIN24_DIR PORT_HIGH
	#define PORT_PIN24_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN25 == PORT_INPUT_PU)
	#define PORT_PIN25_DIR PORT_LOW
	#define PORT_PIN25_PORT PORT_HIGH
#elif (PORT_PIN25 == PORT_INPUT_HI)
	#define PORT_PIN25_DIR PORT_LOW
	#define PORT_PIN25_PORT PORT_LOW
#elif (PORT_PIN25 == PORT_OUTPUT_HIGH)
	#define PORT_PIN25_DIR PORT_HIGH
	#define PORT_PIN25_PORT PORT_HIGH
#elif (PORT_PIN25 == PORT_OUTPUT_LOW)
	#define PORT_PIN25_DIR PORT_HIGH
	#define PORT_PIN25_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN26 == PORT_INPUT_PU)
	#define PORT_PIN26_DIR PORT_LOW
	#define PORT_PIN26_PORT PORT_HIGH
#elif (PORT_PIN26 == PORT_INPUT_HI)
	#define PORT_PIN26_DIR PORT_LOW
	#define PORT_PIN26_PORT PORT_LOW
#elif (PORT_PIN26 == PORT_OUTPUT_HIGH)
	#define PORT_PIN26_DIR PORT_HIGH
	#define PORT_PIN26_PORT PORT_HIGH
#elif (PORT_PIN26 == PORT_OUTPUT_LOW)
	#define PORT_PIN26_DIR PORT_HIGH
	#define PORT_PIN26_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN27 == PORT_INPUT_PU)
	#define PORT_PIN27_DIR PORT_LOW
	#define PORT_PIN27_PORT PORT_HIGH
#elif (PORT_PIN27 == PORT_INPUT_HI)
	#define PORT_PIN27_DIR PORT_LOW
	#define PORT_PIN27_PORT PORT_LOW
#elif (PORT_PIN27 == PORT_OUTPUT_HIGH)
	#define PORT_PIN27_DIR PORT_HIGH
	#define PORT_PIN27_PORT PORT_HIGH
#elif (PORT_PIN27 == PORT_OUTPUT_LOW)
	#define PORT_PIN27_DIR PORT_HIGH
	#define PORT_PIN27_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN28 == PORT_INPUT_PU)
	#define PORT_PIN28_DIR PORT_LOW
	#define PORT_PIN28_PORT PORT_HIGH
#elif (PORT_PIN28 == PORT_INPUT_HI)
	#define PORT_PIN28_DIR PORT_LOW
	#define PORT_PIN28_PORT PORT_LOW
#elif (PORT_PIN28 == PORT_OUTPUT_HIGH)
	#define PORT_PIN28_DIR PORT_HIGH
	#define PORT_PIN28_PORT PORT_HIGH
#elif (PORT_PIN28 == PORT_OUTPUT_LOW)
	#define PORT_PIN28_DIR PORT_HIGH
	#define PORT_PIN28_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN29 == PORT_INPUT_PU)
	#define PORT_PIN29_DIR PORT_LOW
	#define PORT_PIN29_PORT PORT_HIGH
#elif (PORT_PIN29 == PORT_INPUT_HI)
	#define PORT_PIN29_DIR PORT_LOW
	#define PORT_PIN29_PORT PORT_LOW
#elif (PORT_PIN29 == PORT_OUTPUT_HIGH)
	#define PORT_PIN29_DIR PORT_HIGH
	#define PORT_PIN29_PORT PORT_HIGH
#elif (PORT_PIN29 == PORT_OUTPUT_LOW)
	#define PORT_PIN29_DIR PORT_HIGH
	#define PORT_PIN29_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN30 == PORT_INPUT_PU)
	#define PORT_PIN30_DIR PORT_LOW
	#define PORT_PIN30_PORT PORT_HIGH
#elif (PORT_PIN30 == PORT_INPUT_HI)
	#define PORT_PIN30_DIR PORT_LOW
	#define PORT_PIN30_PORT PORT_LOW
#elif (PORT_PIN30 == PORT_OUTPUT_HIGH)
	#define PORT_PIN30_DIR PORT_HIGH
	#define PORT_PIN30_PORT PORT_HIGH
#elif (PORT_PIN30 == PORT_OUTPUT_LOW)
	#define PORT_PIN30_DIR PORT_HIGH
	#define PORT_PIN30_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (PORT_PIN31 == PORT_INPUT_PU)
	#define PORT_PIN31_DIR PORT_LOW
	#define PORT_PIN31_PORT PORT_HIGH
#elif (PORT_PIN31 == PORT_INPUT_HI)
	#define PORT_PIN31_DIR PORT_LOW
	#define PORT_PIN31_PORT PORT_LOW
#elif (PORT_PIN31 == PORT_OUTPUT_HIGH)
	#define PORT_PIN31_DIR PORT_HIGH
	#define PORT_PIN31_PORT PORT_HIGH
#elif (PORT_PIN31 == PORT_OUTPUT_LOW)
	#define PORT_PIN31_DIR PORT_HIGH
	#define PORT_PIN31_PORT PORT_LOW
#else 
	#error "Invalid Configuration"
#endif
	
#if (NUM_OF_PORTS == ONE_PORT)

DDRA=CONCAT(PORT_PIN7_DIR,PORT_PIN6_DIR,PORT_PIN5_DIR,PORT_PIN4_DIR,PORT_PIN3_DIR,PORT_PIN2_DIR,PORT_PIN1_DIR,PORT_PIN0_DIR);
PORTA=CONCAT(PORT_PIN7_PORT,PORT_PIN6_PORT,PORT_PIN5_PORT,PORT_PIN4_PORT,PORT_PIN3_PORT,PORT_PIN2_PORT,PORT_PIN1_PORT,PORT_PIN0_PORT);

#elif (NUM_OF_PORTS == TWO_PORTS)

DDRA=CONCAT(PORT_PIN7_DIR,PORT_PIN6_DIR,PORT_PIN5_DIR,PORT_PIN4_DIR,PORT_PIN3_DIR,PORT_PIN2_DIR,PORT_PIN1_DIR,PORT_PIN0_DIR);
PORTA=CONCAT(PORT_PIN7_PORT,PORT_PIN6_PORT,PORT_PIN5_PORT,PORT_PIN4_PORT,PORT_PIN3_PORT,PORT_PIN2_PORT,PORT_PIN1_PORT,PORT_PIN0_PORT);

DDRB = CONCAT(PORT_PIN15_DIR,PORT_PIN14_DIR,PORT_PIN13_DIR,PORT_PIN12_DIR,PORT_PIN11_DIR,PORT_PIN10_DIR,PORT_PIN9_DIR,PORT_PIN8_DIR);
PORTB = CONCAT(PORT_PIN15_PORT,PORT_PIN14_PORT,PORT_PIN13_PORT,PORT_PIN12_PORT,PORT_PIN11_PORT,PORT_PIN10_PORT,PORT_PIN9_PORT,PORT_PIN8_PORT);

#elif (NUM_OF_PORTS == THREE_PORTS)

DDRA=CONCAT(PORT_PIN7_DIR,PORT_PIN6_DIR,PORT_PIN5_DIR,PORT_PIN4_DIR,PORT_PIN3_DIR,PORT_PIN2_DIR,PORT_PIN1_DIR,PORT_PIN0_DIR);
PORTA=CONCAT(PORT_PIN7_PORT,PORT_PIN6_PORT,PORT_PIN5_PORT,PORT_PIN4_PORT,PORT_PIN3_PORT,PORT_PIN2_PORT,PORT_PIN1_PORT,PORT_PIN0_PORT);

DDRB = CONCAT(PORT_PIN15_DIR,PORT_PIN14_DIR,PORT_PIN13_DIR,PORT_PIN12_DIR,PORT_PIN11_DIR,PORT_PIN10_DIR,PORT_PIN9_DIR,PORT_PIN8_DIR);
PORTB = CONCAT(PORT_PIN15_PORT,PORT_PIN14_PORT,PORT_PIN13_PORT,PORT_PIN12_PORT,PORT_PIN11_PORT,PORT_PIN10_PORT,PORT_PIN9_PORT,PORT_PIN8_PORT);

DDRC = CONCAT(PORT_PIN23_DIR,PORT_PIN22_DIR,PORT_PIN21_DIR,PORT_PIN20_DIR,PORT_PIN19_DIR,PORT_PIN18_DIR,PORT_PIN17_DIR,PORT_PIN16_DIR);
PORTC = CONCAT(PORT_PIN23_PORT,PORT_PIN22_PORT,PORT_PIN21_PORT,PORT_PIN20_PORT,PORT_PIN19_PORT,PORT_PIN18_PORT,PORT_PIN17_PORT,PORT_PIN16_PORT);

#elif (NUM_OF_PORTS == FOUR_PORTS)

DDRA=CONCAT(PORT_PIN7_DIR,PORT_PIN6_DIR,PORT_PIN5_DIR,PORT_PIN4_DIR,PORT_PIN3_DIR,PORT_PIN2_DIR,PORT_PIN1_DIR,PORT_PIN0_DIR);
PORTA=CONCAT(PORT_PIN7_PORT,PORT_PIN6_PORT,PORT_PIN5_PORT,PORT_PIN4_PORT,PORT_PIN3_PORT,PORT_PIN2_PORT,PORT_PIN1_PORT,PORT_PIN0_PORT);

DDRB = CONCAT(PORT_PIN15_DIR,PORT_PIN14_DIR,PORT_PIN13_DIR,PORT_PIN12_DIR,PORT_PIN11_DIR,PORT_PIN10_DIR,PORT_PIN9_DIR,PORT_PIN8_DIR);
PORTB = CONCAT(PORT_PIN15_PORT,PORT_PIN14_PORT,PORT_PIN13_PORT,PORT_PIN12_PORT,PORT_PIN11_PORT,PORT_PIN10_PORT,PORT_PIN9_PORT,PORT_PIN8_PORT);

DDRC = CONCAT(PORT_PIN23_DIR,PORT_PIN22_DIR,PORT_PIN21_DIR,PORT_PIN20_DIR,PORT_PIN19_DIR,PORT_PIN18_DIR,PORT_PIN17_DIR,PORT_PIN16_DIR);
PORTC = CONCAT(PORT_PIN23_PORT,PORT_PIN22_PORT,PORT_PIN21_PORT,PORT_PIN20_PORT,PORT_PIN19_PORT,PORT_PIN18_PORT,PORT_PIN17_PORT,PORT_PIN16_PORT);

DDRD = CONCAT(PORT_PIN31_DIR,PORT_PIN30_DIR,PORT_PIN29_DIR,PORT_PIN28_DIR,PORT_PIN27_DIR,PORT_PIN26_DIR,PORT_PIN25_DIR,PORT_PIN24_DIR);
PORTD = CONCAT(PORT_PIN31_PORT,PORT_PIN30_PORT,PORT_PIN29_PORT,PORT_PIN28_PORT,PORT_PIN27_PORT,PORT_PIN26_PORT,PORT_PIN25_PORT,PORT_PIN24_PORT);

#else 

	#error "Invalid Configuration"

#endif
}

#elif (CONFIG_TYPE == POST_COMPILE)

extern PORT_StrPinCfg_t PORT_StrPinsConfig;

void PORT_vInit()
{
	PORT_enuPorts_t Loc_enuPortNum;
	uint8 Loc_u8PinNum;
	uint8 counter;
	
	for(counter=0;counter<NUM_OF_PINS;counter++)
	{
		Loc_enuPortNum = counter / NUM_OF_PINS_PER_PORT;
		Loc_u8PinNum   = counter % NUM_OF_PINS_PER_PORT;
		switch(Loc_enuPortNum)
		{
			case PORT_enuPortA:
				switch(PORT_StrPinsConfig.PinCfg[counter])
				{
					case PORT_enuInput_PU:
						CLR_BIT(DDRA,Loc_u8PinNum);
						SET_BIT(PORTA,Loc_u8PinNum);
						break;
					case PORT_enuInput_HI:
						CLR_BIT(DDRA,Loc_u8PinNum);
						CLR_BIT(PORTA,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_HIGH:
						SET_BIT(DDRA,Loc_u8PinNum);
						SET_BIT(PORTA,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_LOW:
						SET_BIT(DDRA,Loc_u8PinNum);
						CLR_BIT(PORTA,Loc_u8PinNum);
						break;
					default:
						break;
				}
			case PORT_enuPortB:
				switch(PORT_StrPinsConfig.PinCfg[counter])
				{
					case PORT_enuInput_PU:
						CLR_BIT(DDRB,Loc_u8PinNum);
						SET_BIT(PORTB,Loc_u8PinNum);
						break;
					case PORT_enuInput_HI:
						CLR_BIT(DDRB,Loc_u8PinNum);
						CLR_BIT(PORTB,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_HIGH:
						SET_BIT(DDRB,Loc_u8PinNum);
						SET_BIT(PORTB,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_LOW:
						SET_BIT(DDRB,Loc_u8PinNum);
						CLR_BIT(PORTB,Loc_u8PinNum);
						break;
					default:
						break;
				}
			case PORT_enuPortC:
				switch(PORT_StrPinsConfig.PinCfg[counter])
				{
					case PORT_enuInput_PU:
						CLR_BIT(DDRC,Loc_u8PinNum);
						SET_BIT(PORTC,Loc_u8PinNum);
						break;
					case PORT_enuInput_HI:
						CLR_BIT(DDRC,Loc_u8PinNum);
						CLR_BIT(PORTC,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_HIGH:
						SET_BIT(DDRC,Loc_u8PinNum);
						SET_BIT(PORTC,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_LOW:
						SET_BIT(DDRC,Loc_u8PinNum);
						CLR_BIT(PORTC,Loc_u8PinNum);
						break;
					default:
						break;
			}
			case PORT_enuPortD:
				switch(PORT_StrPinsConfig.PinCfg[counter])
				{
					case PORT_enuInput_PU:
						CLR_BIT(DDRD,Loc_u8PinNum);
						SET_BIT(PORTD,Loc_u8PinNum);
						break;
					case PORT_enuInput_HI:
						CLR_BIT(DDRD,Loc_u8PinNum);
						CLR_BIT(PORTD,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_HIGH:
						SET_BIT(DDRD,Loc_u8PinNum);
						SET_BIT(PORTD,Loc_u8PinNum);
						break;
					case PORT_enuOUTPUT_LOW:
						SET_BIT(DDRD,Loc_u8PinNum);
						CLR_BIT(PORTD,Loc_u8PinNum);
						break;
					default:
						break;
				}
			default:
				break;
		}
	}
}

#else

	#error "Invalid Configuration Type"

#endif